// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | MaterialbasedSlice
  | Project3DSlice
  | PrintsSlice
  | Hero1Slice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Primary content in *Hero1 → Default → Primary*
 */
export interface Hero1SliceDefaultPrimary {
  /**
   * First Name field in *Hero1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.default.primary.first_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *Hero1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.default.primary.last_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_name: prismic.KeyTextField;

  /**
   * Tag Line field in *Hero1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.default.primary.tag_line
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_line: prismic.KeyTextField;

  /**
   * Tag Line Description field in *Hero1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero1.default.primary.tag_line_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_line_description: prismic.KeyTextField;
}

/**
 * Default variation for Hero1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero1*
 */
type Hero1SliceVariation = Hero1SliceDefault;

/**
 * Hero1 Shared Slice
 *
 * - **API ID**: `hero1`
 * - **Description**: Hero1
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero1Slice = prismic.SharedSlice<"hero1", Hero1SliceVariation>;

/**
 * Default variation for Materialbased Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MaterialbasedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Materialbased*
 */
type MaterialbasedSliceVariation = MaterialbasedSliceDefault;

/**
 * Materialbased Shared Slice
 *
 * - **API ID**: `materialbased`
 * - **Description**: Materialbased
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MaterialbasedSlice = prismic.SharedSlice<
  "materialbased",
  MaterialbasedSliceVariation
>;

/**
 * Primary content in *Prints → Default → Primary*
 */
export interface PrintsSliceDefaultPrimary {
  /**
   * DataTitle field in *Prints → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.datatitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  datatitle: prismic.KeyTextField;

  /**
   * Data Description field in *Prints → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.data_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  data_description: prismic.KeyTextField;

  /**
   * Main Image field in *Prints → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Full Size Image field in *Prints → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.full_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  full_image: prismic.ImageField<never>;

  /**
   * Small Image 1 field in *Prints → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.small_image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  small_image_1: prismic.ImageField<never>;

  /**
   * Small Image 2 field in *Prints → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prints.default.primary.small_image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  small_image_2: prismic.ImageField<never>;
}

/**
 * Default variation for Prints Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrintsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrintsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Prints*
 */
type PrintsSliceVariation = PrintsSliceDefault;

/**
 * Prints Shared Slice
 *
 * - **API ID**: `prints`
 * - **Description**: Prints
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrintsSlice = prismic.SharedSlice<"prints", PrintsSliceVariation>;

/**
 * Primary content in *Project3D → Default → Primary*
 */
export interface Project3DSliceDefaultPrimary {
  /**
   * Title3d field in *Project3D → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project3_d.default.primary.title3d
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title3d: prismic.KeyTextField;

  /**
   * Description3d field in *Project3D → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project3_d.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Project3D Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Project3DSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Project3DSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Project3D*
 */
type Project3DSliceVariation = Project3DSliceDefault;

/**
 * Project3D Shared Slice
 *
 * - **API ID**: `project3_d`
 * - **Description**: Project3D
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Project3DSlice = prismic.SharedSlice<
  "project3_d",
  Project3DSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ExperienceSlice,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      Hero1Slice,
      Hero1SliceDefaultPrimary,
      Hero1SliceVariation,
      Hero1SliceDefault,
      MaterialbasedSlice,
      MaterialbasedSliceVariation,
      MaterialbasedSliceDefault,
      PrintsSlice,
      PrintsSliceDefaultPrimary,
      PrintsSliceVariation,
      PrintsSliceDefault,
      Project3DSlice,
      Project3DSliceDefaultPrimary,
      Project3DSliceVariation,
      Project3DSliceDefault,
    };
  }
}
