// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  experience: dynamic(() => import("./Experience")),
  hero1: dynamic(() => import("./Hero1")),
  materialbased: dynamic(() => import("./Materialbased")),
  prints: dynamic(() => import("./Prints")),
  project3_d: dynamic(() => import("./Project3D")),
};
